name: gh.build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
    steps:
      - uses: actions/checkout@v1
      - name: install-beta
        run: rustup toolchain install beta
      - name: use-beta
        run: rustup default beta
      - name: build
        run: cargo build
      - name: test
        run: cargo test
